### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Strahilchu** [FeuSalamander/Vmessage#1]
I tried it on my network and I wasn't able to send any chat messages at all.

No errors, no clue

**Comment by Strahilchu** [comment]
venturechat was in the way

**Comment by FeuSalamander** [comment]
Does it works or you still have the problem ? (the message doesn't appear on the server where the player is)

**Comment by Strahilchu** [comment]
> Does it works or you still have the problem ? (the message doesn't appear on the server where the player is)

It works now I just had to remove VentureChat :)
