### ISSUE TITLE
[Feature Request] 1.20.1 Support

### ISSUE THREAD

**Issue by 0x7d8** [FeuSalamander/Vmessage#11]
Title says it all - add 1.20.1 support

**Comment by FeuSalamander** [comment]
Did you already tested it ?

**Comment by 0x7d8** [comment]
yup, Im getting this
![grafik](https://github.com/FeuSalamander/Vmessage/assets/63073556/06b7fde9-92fd-4258-b557-b8e59cc6f08a)

**Comment by FeuSalamander** [comment]
I normally fixed your issue, the new release is the Vmessage 1.5.6 Pre you can test it now and if it works I will set it as the latest release

**Comment by 0x7d8** [comment]
works perfectly.
