### ISSUE TITLE
[FEATURE] Config with Options

### ISSUE THREAD

**Issue by Strahilchu** [FeuSalamander/Vmessage#2]
Would like to see this plugin have a config with the following options (if possible)
Updater: true/false
Metrics: true/false
Chat format: (Server) 
aka be able to change how chat messages display across servers, or even have placeholder support

**Comment by FeuSalamander** [comment]
ok I will try to implement it, thanks for your feature request ! :)

**Comment by FeuSalamander** [comment]
I done it ! so now you have a config file to configure the display message
