### ISSUE TITLE
[Feature request] Execute command instead of sending a message

### ISSUE THREAD

**Issue by Folas1337** [FeuSalamander/Vmessage#9]
I'm running a multi proxy setup and it would be absolutely wonderful if instead of sending a message which is only seen on one proxy, I could execute a command which would allow me to use ConnectorPlugin which in turn would let me send a redis message for all proxies so it would show a message such as "#player# joined the network".

Basically the config would allow me to do this:
```
[...]
[Join]
command = "connectorpluginvelocity proxycommand broadcast minimessage <yellow>#prefix# #player# joined the network"
enabled = true
[Leave]
command = "connectorpluginvelocity proxycommand broadcast minimessage <yellow>#prefix# #player# left the network"
enabled = true
[Server-change]
command = "connectorpluginvelocity proxycommand broadcast minimessage <yellow>#prefix# #player# switched from #oldserver# to #server#"
enabled = true
[...]
```

That would be a huge benefit to my network <3

**Comment by FeuSalamander** [comment]
So if I understood you want me to add an option in the config to instead of sending the message it will do command of Connector Plugin ?

**Comment by Folas1337** [comment]
I also realized it's limited to 1 command isn't it? If it could be made an array of commands, that would be sweet.
So I could do:
```
[Join]
command:
  - "connectorpluginvelocity proxycommand broadcast minimessage <yellow>#prefix# #player# joined the network"
  - "connectorpluginvelocity servercommand lobby1 discordsrv broadcast #player# joined the network"
enabled = true
```
That way I could also send a little Discord message that someone joined or left the network :)

**Comment by FeuSalamander** [comment]
Did it, it should works, you can test it by installing the last version 1.5.4

**Comment by Folas1337** [comment]
That's pretty good already, now we just have to fix two more things:
1. #player# should be parsed before the command is sent, so it doesn't literally say #player# and instead replaces it with the player.
2. Make it so that if format is set to an empty string, it will not send an empty line.
Basically means that if I use this config snippet, it should not send any message:
```
format = ""
```

I will quite certainly be fully satisfied after that :)

**Comment by Folas1337** [comment]
... and of course as I say that, I have to bring up another little annoyance of mine.
If I ban someone with LibertyBans and they try to join, it still shows them as "#player# left the network." which isn't exactly ideal as I don't want to know if someone who never really made it is disconnected.

Is there anything you can do to prevent that from happening? Wait for a certain event (such as authentication or whatever there might be in the process of joining) to happen and only then send the message?

Sorry this is such a hassle, I just want to make this a solid solution :)

**Comment by FeuSalamander** [comment]
Dajokni fixed the problem due to the ban and for your 2 other problems I will fix them, they appeared because I just added rough command and not really added it for your case and in the config it's a list, you just have to do ´commands = [ "1", "2"]

**Comment by Folas1337** [comment]
I'm not sure if I'll get around to it today, I should be able to by tomorrow and I'll let you know how my tests went 👍
Thanks for the really quick work so far, I'm so happy to see motivated developers :)

**Comment by Folas1337** [comment]
Works flawlessly for me, thank you so much <3
